#14 remove french spelling errors
statikbe/craft-cookie-banner pull request #16
Opened 2024-01-12 13:24 UTC by Numkil

### Description

fixes #14

2024-03-12 07:24 UTC, HannahDeWachter requested changes
De **N'** op lijn 7 moet er niet zijn volgens mij. Dit zou op een negatie wijzen, wat het niet is.

2024-04-18 08:36 UTC, Numkil commented
@HannahDeWachter 

Volgens het issue waarop deze PR gebaseerd is is de change op lijn 7 de juiste manier om het te zeggen in het frans :) Kan je deze approven? 
<img width="691" alt="Screenshot 2024-04-18 at 10 35 42" src="https://github.com/statikbe/craft-cookie-banner/assets/5604686/4d04fe6c-07ec-456e-bf1a-6ae8d6bb0020">

2024-04-18 08:46 UTC, janhenckens approved these changes

2024-04-18 08:51 UTC, HannahDeWachter approved these changes

2024-04-18 08:54 UTC, merged